BankConverter.UI/Models/CalculateRatesResponseViewModel.cs
using System.Text.Json.Serialization;

namespace BankConverter.UI.Models
{
    public class CalculateRatesResponseViewModel
    {
        [JsonPropertyName("rateValue")]
        public decimal RateValue { get; set; }

        [JsonPropertyName("rate")]
        public decimal Rate { get; set; }

        [JsonPropertyName("firtsCurrency")]
        public string FirtsCurrency { get; set; }

        [JsonPropertyName("secondCurrency")]
        public string SecondCurrency { get; set; }

        [JsonPropertyName("amount")]
        public decimal Amount { get; set; }
    }
}

BankConverter.UI/Models/ErrorViewModel.cs
namespace BankConverter.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public string ErrorMessage { get; set; }
    }
}

BankConverter.UI/Models/GetAllRatesResponseModel.cs
using System.Text.Json.Serialization;

namespace BankConverter.UI.Models
{
    public class GetAllRatesResponseModel
    {
        
        [JsonPropertyName("currency")]
        public string Currency { get; set; }

        [JsonPropertyName("value")]
        public decimal Value { get; set; }
    }

}

BankConverter.UI/Models/GetAllRatesViewModel.cs
using System.Text.Json.Serialization;

namespace BankConverter.UI.Models
{
    public class GetAllRatesViewModel
    {
        
        [JsonPropertyName("currency")]
        public string Currency { get; set; }

        [JsonPropertyName("value")]
        public string Value { get; set; }
    }

}

BankConverter.UI/Models/InputCalculateRatesViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace BankConverter.UI.Models
{
    public class InputCalculateRatesViewModel
    {
        public List<GetAllRatesResponseModel> Rates { get; set; }

        public IEnumerable<SelectListItem> CurrenciesToSelect { get; set; }

        public string FirstCurrency { get; set; }

        public string SecondCurrency { get; set; }

        public decimal Value { get; set; }
    }
}

BankConverter.UI/Models/InputRatesViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace BankConverter.UI.Models
{
    public class InputRatesViewModel
    {
        public List<GetAllRatesViewModel> Rates { get; set; }

        public IEnumerable<SelectListItem> CurrenciesToSelect { get; set; }

        public string FirstCurrency { get; set; }

        public string SecondCurrency { get; set; }

        public decimal Value { get; set; }
    }
}

BankConverter.UI/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BankConverter.UI.Models;

namespace BankConverter.UI.Controllers
{
    public class HomeController : Controller
    {

        public HomeController()
        {        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BankConverter.UI/Controllers/RatesController.cs
using BankConverter.UI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace BankConverter.UI.Controllers
{
    public class RatesController : Controller
    {
        public RatesController()
        {        }

        public async Task<IActionResult> LoadRates()
        {
            var httpClient = new HttpClient();
            var result = new InputCalculateRatesViewModel();
            try
            {
                var response = await httpClient.GetAsync("https://localhost:44302/api/DataLoad/GetAllCurrencies");

                var rates = JsonSerializer.Deserialize<List<GetAllRatesResponseModel>>(response.Content.ReadAsStringAsync().Result);

                result.Rates = rates;
                result.CurrenciesToSelect = rates.
                        Select(i => new SelectListItem()
                        {
                            Text = i.Currency.ToString(),
                            Value = i.Currency
                        });
            }
            catch
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "Error loading data"});
            }

            return View(result);
        }

        public async Task<IActionResult> CalculatedRates(InputCalculateRatesViewModel input)
        {
            var httpClient = new HttpClient();
            var result = new CalculateRatesResponseViewModel();
            try
            {
                var data = JsonSerializer.Serialize(input);
                var content = new StringContent(data, Encoding.UTF8, "application/json");
                var response = await httpClient.PostAsync("https://localhost:44302/api/Rate/CalculateRates", content);

                result = JsonSerializer.Deserialize<CalculateRatesResponseViewModel>(response.Content.ReadAsStringAsync().Result);
            }
            catch
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "Error converting rates" });
            }

            return View(result);
        }
    }
}

BankConverter.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BankConverter.UI/Views/Rates/CalculatedRates.cshtml
@model CalculateRatesResponseViewModel
<h1>Calculated rates result</h1>
<div>
    <div>Result from @Model.FirtsCurrency to @Model.SecondCurrency and amount @Model.Amount is @Model.RateValue Rate is @Model.Rate</div>
</div>
<input id="calculateNewBtn" type="button" value="Calculate new" />
<script type="text/javascript">
    $('#calculateNewBtn').click(function () {
        document.location = '@Url.Action("LoadRates","Rates")';
    });
</script>

BankConverter.UI/Views/Rates/LoadRates.cshtml
@model InputCalculateRatesViewModel

@using (Html.BeginForm("CalculatedRates", "Rates", FormMethod.Post,  new { enctype = "multipart/form-data" }))
{
    <table>
        <tr>
            @Html.LabelFor(model => model.FirstCurrency, new { @class = "control-label col-md-2" })
            @Html.DropDownListFor(model => model.FirstCurrency, new SelectList(Model.CurrenciesToSelect, "Value", "Text"))
        </tr>
        <tr>
            @Html.LabelFor(model => model.Value, new { @class = "control-label col-md-2" })
            @Html.TextBoxFor(model => model.Value, new { @pattern = @"\d+" })
            @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
        </tr>
        <tr>
            @Html.LabelFor(model => model.SecondCurrency, new { @class = "control-label col-md-2" })
            @Html.DropDownListFor(model => model.SecondCurrency, new SelectList(Model.CurrenciesToSelect, "Value", "Text"))
        </tr>
    </table>
    <input type="submit" value="Calculate" />
}

BankConverter.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BankConverter.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="https://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Rates" asp-action="LoadRates">BankConverter.UI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BankConverter.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>